### ISSUE TITLE
> This should now be addressed. Thank you for the feedback.

### ISSUE THREAD

**Issue by secure-clouds** [1Strategy/efs-starter-template#3]
> This should now be addressed. Thank you for the feedback.
That was prompt! 👍 The issue still remains open though. If I were to use this template, the ThroughputMode as Provisioned would work fine. The trouble then is the the Bursted mode. Now, the template can't be deployed because the ProvisionedThroughPutInMibps would be empty. (The template won't even reach "AWS::NoValue")

_Originally posted by @avi26-git in https://github.com/1Strategy/efs-starter-template/issues/1#issuecomment-678088649_

**Comment by jiravani** [comment]
Both bursting and provisioned have been tested successfully. Please try the template and post your results here.
